version: 0.2

phases:
    build:
        commands:
            - echo "assignment for 2nd roud"
    post_build:
        commands:
            - echo "deployed to s3"
artifacts:
    files:
        - "**/**"
