version: 0.2

phases:
        build:
                commands:
                        - unset CI
                        - npm install
                        - npm run build

        post_build:
                commands:
                        - echo "deployed to s3"
artifacts:
        files:
                - build/**
