version: 0.2

phases:
  install:
    commands:
     # - echo install node 12...
     # - curl -sL https://deb.nodesource.com/setup_12.x | bash -
     # - apt install -y nodejs
     # - echo install yarn...
      - npm install --global yarn

  pre_build:
    commands:
      - echo installing dependencies...
      - yarn
  build:
    commands:
     # - yarn test
      - yarn build
artifacts:
  files:
    #- "**/*"
    - build/**
